### ISSUE TITLE
Proposal: replace the dataframe dictionary with a NamedTuple

### ISSUE THREAD

**Issue by thomkeh** [predictive-analytics-lab/EthicML#16]
Dictionaries always have the problem that you can store anything in there and you can also store nothing in there. `dictionary['x']` can always fail.

NamedTuple on the other hand have a fixed number of fields and all fields are mandatory:

```python
from typing import NamedTuple
import pandas as pd

class DataTuple(NamedTuple):
    x: pd.DataFrame
    y: pd.DataFrame
    s: pd.DataFrame
```

They are instantiated as follows:

```python
data = DataTuple(x=df1, y=df2, s=df3)
```

The values are accessed like this:
```python
data.x
```

Finally, NamedTuple are *immutable*. This: `data.x = df4` throws an error.

**Comment by olliethomas** [comment]
Then the type of data will be `data: NamedTuple[str, pd.DataFrame]` ?

**Comment by thomkeh** [comment]
Done in #22
