### ISSUE TITLE
Agarwal doesn't work anymore with the newest version

### ISSUE THREAD

**Issue by thomkeh** [predictive-analytics-lab/EthicML#225]
It gives this error:

```
    """Implementation of logistic regression (actually just a wrapper around sklearn)"""
    import pandas as pd

>   from fairlearn.classred import expgrad
E   ModuleNotFoundError: No module named 'fairlearn.classred'

ethicml/implementations/agarwal.py:4: ModuleNotFoundError
```

**Comment by thomkeh** [comment]
It might be as simple as doing

```python
from fairlearn.reductions import ExponentiadedGradients
```

instead.

**Comment by romanlutz** [comment]
@thomkeh @olliethomas  we have converted fairlearn into a package that provides a variety of unfairness  mitigation techniques as opposed to just the ExponentiatedGradient method. It's actually similar to ethicml in terms of objective. If you're interested in collaborating on a single effort we'd be more than happy to discuss.

**Comment by olliethomas** [comment]
@romanlutz sure. Feel free to send us an email ot44 (at) sussex (dot) ac (dot) uk, and t (dot) kehrenberg (at) sussex (dot) ac (dot) uk to discuss further
