### ISSUE TITLE
run_metrics should return a df instead of a dict

### ISSUE THREAD

**Issue by olliethomas** [predictive-analytics-lab/EthicML#344]
There's already a suggestion in teh code for this, just making an issue for it

https://github.com/predictive-analytics-lab/EthicML/blob/master/ethicml/evaluators/evaluate_models.py#L87

One potential problem with dicts is that really the values should be sorted when for example writing to file, which is really the most likely thing to do with some metrics.

**Comment by thomkeh** [comment]
One problem with this is that the dictionary is useful for logging to W&B.

**Comment by thomkeh** [comment]
I think I decided against this.
