### ISSUE TITLE
Proposal: Multiple S

### ISSUE THREAD

**Issue by olliethomas** [predictive-analytics-lab/EthicML#353]
### Abstract
We currently only really support one group of binary S values. FairML literature has a large gap in terms of analysis of a more real-world setup: multiple groups of S. This proposal is for multiple S groups, which in turn are exclusive, to be supported.

For example, currently we have `{gender=0, gender=1}`. This has recently been extended to include more than one sensitive group, `{race0-gender0=0, race1-gender0=1, race2-gender0=2, race0-gender1=3, race1-gender1=4, race2-gender1=5}`. 

This proposal is to formalise this process a little.

### Motivation 
Fairness and Equality laws around the world consider multiple sensitive groups. For example you should be fair with regard to race, gender AND religion (amongst others). But how to best represent this? 

### Specification 

The recent approach is to combine all potential groups giving N sensitive values. During training we can potentially OHE the sensitive value, and during evaluation we can then treat the result as a (1v1/1vA) binary problem. Throughout we can use a lookup table to map back from 3 -> race=1, gender=1. This lookup table would exist as part of the created Dataset object.

#### Lookup Table

The lookup table should map between 2 tables. One which is held in DataTupleInstance.s, and another, more readable one

_DataTupleInstance.s_
| Index | S |
|:-----:|:-:|
|     0 | 0 |
|     1 | 4 |
|     2 | 3 |
|     3 | 1 |
|     4 | 3 |
|     5 | 5 |
|     6 | 2 |
| ...| ...|

There should be a mapping between these 2 tables

_readable_
|       | Gender  |         | Race  |       | |
|-------|---------|---------|-------|-------|-----|
| Index | Gender0 | Gender1 | Race0 | Race1 | Race2 |
|     0 |    1    | 0       | 1     | 0     | 0 |
|     1 |    0    | 1       | 0     | 1     | 0 |
|     2 |    0    | 1       | 1     | 0     | 0 |
|     3 |    1    | 0       | 0     | 1     | 0 |
|     4 |    0    | 1       | 1     | 0     | 0 |
|     5 |    0    | 1       | 0     | 0     | 1 |
|     6 |    1    | 0       | 0     | 0     | 1 |
|     ... |   ...    | ...       | ...     | ...     | ... |

Why multi-hierarchy? This will make it easier to look at just Gender, or just Race

#### Evaluation Metrics
If you're woking on intersectional data groups, then we will need this mapping to produce metrics that are readable. The `run_metrics` helper should optionally accept a Dataset object. If it receives this, then the data should be unpacked prior to reporting the values. If a dataset is not provided, then the evaluations should not try to map from a number `15` to a text description `sex=value0,gender=value0,nationality=value15`.

### Rejected Ideas 

Not collapsing the intersectional groups and leaving just the hierarchical 

### Outstanding Problems

How to extend to continuous S? - We don't have any datasets where this is the case, so not a primary concern.

What if, as a user, I don't want to create a lookup mechanism? I just want to get some metrics for the data I put in? - These lookup tables will be provided for all datasets in EthicML. Unless you're loading in your own data directly into a DataTuple, in which case if no Dataset is provided to one of the evaluation helpers, then the values are assumed to belong to one S group.

What if I have an S group which has no value, or a missing value? This will need to be remedied prior to using EthicML. We assume that each sensitive group has exactly one value per row.

**Comment by thomkeh** [comment]
Developing this further, the mapping could be specified like this:

```python
class SensSpec(NamedTuple):
    """Specification for a sensitive attribute."""

    multiplier: int
    columns: List[str]


def adult_sex_race() -> Dataset:
    s_mapping = {
        "race": SensSpec(multiplier=1, columns=[
            "race_Amer-Indian-Eskimo",
            "race_Asian-Pac-Islander",
            "race_Black",
            "race_Other",
            "race_White",
        ]),
        "sex": SensSpec(multiplier=5, columns=["Sex_Male"]),
    }
    return Dataset(
        name="Adult, race-sex",
        # ...
        s_mapping=s_mapping,
    )
```

Then, `Dataset.load()` would do something like this:

```python
def load(self):
    # ...
    s = pd.DataFrame(np.zeros())
    for _, spec in self.s_mapping.items():
        values = undo_one_hot(all_data[spec.columns])
        s += spec.multiplier * values
    # ...
```

The `undo_one_hot()` is needed in order to combine all relevant columns into one number which we can then multiply with the multiplier.

The inverse mapping is a bit trickier.

```python
def undo_s_mapping(s: pd.Series, s_mapping: Dict[str, SensSpec]):
    final_df = {}
    for sens, spec in s_mapping.items():
        value = (s % (spec.multiplier + 1)) // spec.multiplier
        restored = one_hot(value)
        restored.columns = spec.columns
        final_df[sens] = restored  # for the multi-level column index

    return pd.concat(final_df, axis=1)
```
