### ISSUE TITLE
The release packaged with poetry contains the raw CSV files, making it quite big

### ISSUE THREAD

**Issue by thomkeh** [predictive-analytics-lab/EthicML#435]
Now that #429 has been merged, I created a new release and built and published it with poetry. However, while with setup.py, the wheel was 38MB, with poetry it's 88MB. This is most likely because of `ethicml/data/csvs/raw/health.csv`, which is a very large file and which was previously not included in the wheel.

**Comment by olliethomas** [comment]
What's your thinking? git large file storage, or maybe DVC? Or download the files the first time that they are used?

**Comment by thomkeh** [comment]
Ah, you misunderstand. We just have to tell poetry to exclude `ethicml/data/csvs/raw`. Those files are not actually needed. There is a processed version of `health.csv` in `ethicml/data/csvs` which is all that's needed.

**Comment by thomkeh** [comment]
I assume it's as easy as
```
exclude = ["ethicml/data/csvs/raw/*"]
```

**Comment by thomkeh** [comment]
It's back down to under 38MB:

![image](https://user-images.githubusercontent.com/7741417/121922572-015f1700-cd32-11eb-8483-e1a68ffc4005.png)

🎉
