### ISSUE TITLE
(0.7.1) Unable to cross-validate SVM with reweighing/Kamiran

### ISSUE THREAD

**Issue by HammondOT** [predictive-analytics-lab/EthicML#586]
When running `validator = em.CrossValidator(em.Kamiran(classifier='SVM', kernel='linear'), hps, folds=5)` and using `hps = {"C": [10, 2, 1, 0.1, 1e-2]}`, the result is:

```
[/usr/local/lib/python3.7/dist-packages/ethicml/evaluators/cross_validator.py](https://localhost:8080/#) in run(self, train, measures)
    243             for experiment in self.experiments:
    244                 # instantiate model and run it
--> 245                 model = self.model(**experiment)
    246                 preds = model.run(train_fold, val)
    247                 scores = compute_scores_and_append(experiment, preds, val, i)

TypeError: 'Kamiran' object is not callable
```

If I simply do `validator = em.CrossValidator(em.Kamiran, hps, folds=5)`, the crossvalidation defaults to Kamiran & Calders LR. I have attempted it with `em.SVM`, `em.LR`, and `em.MLP`, and all work fine - but they don't take any arguments in em.CrossValidator. Is this expected behaviour?

ta x

**Comment by olliethomas** [comment]
Hi, thanks for raising the issue. The problem is with how the `CrossValidator` is being called. It accepts a class type (an uninstantiated class). The arguments to be evaluated are provided via the hyperparameters dictionary. So here, you would need to specify the internal classifier via that mechanism
```
validator = em.CrossValidator(
                model=em.Kamiran, 
                hyperparameters={
                    "classifier": ["SVM"], 
                    "kernel": ["linear"], 
                    "C": [10, 2, 1, 0.1, 1e-2]
                }, 
                folds=5
            )
```
