### ISSUE TITLE
Proposal: algorithm in separate processes

### ISSUE THREAD

**Issue by thomkeh** [predictive-analytics-lab/EthicML#9]
I imagine running algorithms in separate processes to work something like this:

At the end of the data preparation, the data is stored on the hard drive:

```python
with TemporaryDirectory() as tmpdir:
    tmp_path = Path(tmpdir)
    data_path = tmp_path / Path("data.parquet")
    df = pd.concat([data_dict['x'], data_dict['s'], data_dict['y']], axis='columns')
    df.to_parquet(data_path, compression=None)
```

Then a python script for the algorithm is started as a separate process. The path to the data file is passed as a commandline argument.

```python
from subprocess import call
PYTHON_EXE = "/home/ubuntu/anaconda3/envs/pytorch_p36/bin/python -u"

...

cmd = f"{PYTHON_EXE} {script_path} {data_path}"
call(cmd, shell=True)
```

Then the data file is read by the called script.

```python
import sys
import pandas as pd

...

data_path = sys.argv[1]
with open(data_path, 'rb') as f:
df = pd.read_parquet(data_path)
```

(`parquet` has to be install with `pip install fastparquet`.)

**Comment by thomkeh** [comment]
More info on Parquet:

> Parquet is designed to faithfully serialize and de-serialize `DataFrame` s, supporting all of the pandas dtypes, including extension dtypes such as datetime with tz.

> Several caveats.

> * Duplicate column names and non-string columns names are not supported.
> * Index level names, if specified, must be strings.
> * Categorical dtypes can be serialized to parquet, but will de-serialize as `object` dtype.
> * Non supported types include `Period` and actual Python object types. These will raise a helpful error message on an attempt at serialization.

http://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#io-parquet

**Comment by olliethomas** [comment]
I think this looks like a good idea. If we want to be able to have many jobs over the HPC then this will become necessary so best to get it in early

**Comment by thomkeh** [comment]
this has been started in #17 . closing this.
